services:
  backend:
    build:
      context: owl/
      dockerfile: Dockerfile
    image: owl
    container_name: parakeet-backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./owl/:/usr/src/app/ # need help with this
      - /usr/src/app/node_modules # need help with this
    ports:
      - "8000:8000"
    env_file: owl/.env
    environment:
      - NODE_ENV=development
      - HUGGINGFACE_HUB_TOKEN=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
    networks:
      - parakeet-network #is this right?

  frontend:
    build:
      context: falcon/
      dockerfile: Dockerfile
    image: falcon-frontend
    container_name: parakeet-frontend
    command: npm start
    volumes:
      - ./falcon/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000/api/v1
      - NEXT_PUBLIC_API_URL=http://backend:8000/api/v1
    env_file: falcon/.env.local
    networks:
      - parakeet-network

networks:
  parakeet-network:
    driver: bridge
